=== odow/MathOptFormat.jl/src/MOF/schema/mof.schema.json
{
    "$schema": "https://json-schema.org/schema#",
    "$id": "https://github.com/odow/MathOptFormat.jl/tree/master/src/MOF/mof.schema.json",
    "title": "The schema for MathOptFormat",
    "type": "object",
    "required": ["version", "variables", "objectives", "constraints"],
    "properties": {
        "version": {
            "description": "The version of MathOptFormat that this schema validates against.",
            "const": 0
        },
        "name": {
            "description": "The name of the model.",
            "type": "string"
        },
        "author": {
            "description": "The author of the model for citation purposes.",
            "type": "string"
        },
        "description": {
            "description": "A human-readable description of the model.",
            "type": "string"
        },
        "variables": {
            "description": "An array of variables in the model. Each must have a unique name.",
            "type": "array",
            "items": {
                "type": "object",
                "required": ["name"],
                "properties": {
                    "name": {
                        "type": "string"
                    }
                }
            },
            "uniqueItems": true
        },
        "objectives": {
            "description": "An array of objectives in the model.",
            "type": "array",
            "items": {
                "type": "object",
                "required": ["sense", "function"],
                "properties": {
                    "sense": {
                        "enum": ["min", "max"]
                    },
                    "function": {
                        "$ref": "#/definitions/scalar_functions"
                    }
                }
            }
        },
        "constraints": {
            "description": "An array of constraints in the model. Scalar-valued functions can only be paired with scalar-sets, and the same applies for vector-valued functions and sets.",
            "type": "array",
            "items": {
                "type": "object",
                "required": ["function", "set"],
                "properties": {
                    "name": {
                        "type": "string"
                    }
                },
                "oneOf": [{
                    "description": "A scalar-valued constraint.",
                    "properties": {
                        "function": {
                            "$ref": "#/definitions/scalar_functions"
                        },
                        "set": {
                            "$ref": "#/definitions/scalar_sets"
                        }
                    }
                }, {
                    "description": "A vector-valued constraint.",
                    "properties": {
                        "function": {
                            "$ref": "#/definitions/vector_functions"
                        },
                        "set": {
                            "$ref": "#/definitions/vector_sets"
                        }
                    }
                }]
            },
            "uniqueItems": true
        }
    },
    "definitions": {
        "ScalarAffineTerm": {
            "description": "A helper object that represents `coefficent * variable`.",
            "type": "object",
            "required": ["coefficient", "variable"],
            "properties": {
                "coefficient": {
                    "type": "number"
                },
                "variable": {
                    "type": "string"
                }
            }
        },
        "ScalarQuadraticTerm": {
            "description": "A helper object that represents `coefficent * variable_1 * variable_2`.",
            "type": "object",
            "required": ["coefficient", "variable_1", "variable_2"],
            "properties": {
                "coefficient": {
                    "type": "number"
                },
                "variable_1": {
                    "type": "string"
                },
                "variable_2": {
                    "type": "string"
                }
            }
        },
        "VectorAffineTerm": {
            "description": "A helper object that represents a `ScalarAffineTerm` in row `output_index`.",
            "type": "object",
            "required": ["output_index", "scalar_term"],
            "properties": {
                "output_index": {
                    "type": "integer",
                    "minimum": 1
                },
                "scalar_term": {
                    "$ref": "#/definitions/ScalarAffineTerm"
                }
            }
        },
        "VectorQuadraticTerm": {
            "description": "A helper object that represents a `ScalarQuadraticTerm` in row `output_index`.",
            "type": "object",
            "required": ["output_index", "scalar_term"],
            "properties": {
                "output_index": {
                    "type": "integer",
                    "minimum": 1
                },
                "scalar_term": {
                    "$ref": "#/definitions/ScalarQuadraticTerm"
                }
            }
        },
        "NonlinearTerm": {
            "description": "A node in an expresion graph representing a nonlinear function.",
            "type": "object",
            "required": ["head"],
            "oneOf": [{
                "description": "Unary operators.",
                "required": ["args"],
                "properties": {
                    "head": {
                        "enum": [
                            "log", "log10", "exp", "sqrt", "floor", "ceil",
                            "abs", "cos", "sin", "tan", "acos", "asin", "atan",
                            "cosh", "sinh", "tanh", "acosh", "asinh", "atanh"
                        ]
                    },
                    "args": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/NonlinearTerm"
                        },
                        "minItems": 1,
                        "maxItems": 1
                    }
                }
            }, {
                "description": "Binary operators.",
                "required": ["args"],
                "properties": {
                    "head": {
                        "enum": ["/", "^"]
                    },
                    "args": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/NonlinearTerm"
                        },
                        "minItems": 2,
                        "maxItems": 2
                    }
                }
            }, {
                "description": "N-ary operators.",
                "required": ["args"],
                "properties": {
                    "head": {
                        "enum": ["+", "-", "*", "min", "max"]
                    },
                    "args": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/NonlinearTerm"
                        },
                        "minItems": 1
                    }
                }
            }, {
                "description": "A real-valued numeric constant.",
                "required": ["value"],
                "properties": {
                    "head": {
                        "const": "real"
                    },
                    "value": {
                        "type": "number"
                    }
                }
            }, {
                "description": "A complex-valued numeric constant.",
                "required": ["real", "imag"],
                "properties": {
                    "head": {
                        "const": "complex"
                    },
                    "real": {
                        "type": "number"
                    },
                    "imag": {
                        "type": "number"
                    }
                }
            }, {
                "description": "A reference to an optimization variable",
                "required": ["name"],
                "properties": {
                    "head": {
                        "const": "variable"
                    },
                    "name": {
                        "type": "string"
                    }
                }
            }, {
                "description": "A pointer to a (1-indexed) element in the `node_list` field in a nonlinear function",
                "required": ["index"],
                "properties": {
                    "head": {
                        "const": "node"
                    },
                    "index": {
                        "type": "integer",
                        "minimum": 1
                    }
                }
            }]
        },
        "scalar_functions": {
            "description": "A schema for the scalar-valued functions defined by MathOptFormat.See http://www.juliaopt.org/MathOptInterface.jl/v0.8/apireference/#Functions-and-function-modifications-1 for a list of the functions and their meanings.",
            "type": "object",
            "required": ["head"],
            "oneOf": [{
                "required": ["variable"],
                "properties": {
                    "head": {
                        "const": "SingleVariable"
                    },
                    "variable": {
                        "type": "string"
                    }
                }
            }, {
                "required": ["constant", "terms"],
                "properties": {
                    "head": {
                        "const": "ScalarAffineFunction"
                    },
                    "constant": {
                        "type": "number"
                    },
                    "terms": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/ScalarAffineTerm"
                        }
                    }
                }
            }, {
                "required": ["constant", "affine_terms", "quadratic_terms"],
                "properties": {
                    "head": {
                        "const": "ScalarQuadraticFunction"
                    },
                    "constant": {
                        "type": "number"
                    },
                    "affine_terms": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/ScalarAffineTerm"
                        }
                    },
                    "quadratic_terms": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/ScalarQuadraticTerm"
                        }
                    }
                }
            }, {
                "required": ["root", "node_list"],
                "properties": {
                    "head": {
                        "const": "Nonlinear"
                    },
                    "root": {
                        "$ref": "#/definitions/NonlinearTerm"
                    },
                    "node_list": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/NonlinearTerm"
                        }
                    }
                }
            }]
        },
        "vector_functions": {
            "description": "A schema for the vector-valued functions defined by MathOptFormat.See http://www.juliaopt.org/MathOptInterface.jl/v0.8/apireference/#Functions-and-function-modifications-1 for a list of the functions and their meanings.",
            "type": "object",
            "required": ["head"],
            "oneOf": [{
                "required": ["variables"],
                "properties": {
                    "head": {
                        "const": "VectorOfVariables"
                    },
                    "variables": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            }, {
                "required": ["constants", "terms"],
                "properties": {
                    "head": {
                        "const": "VectorAffineFunction"
                    },
                    "constants": {
                        "type": "array",
                        "items": {
                            "type": "number"
                        }
                    },
                    "terms": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/VectorAffineTerm"
                        }
                    }
                }
            }, {
                "required": ["constants", "affine_terms", "quadratic_terms"],
                "properties": {
                    "head": {
                        "const": "VectorQuadraticFunction"
                    },
                    "constants": {
                        "type": "array",
                        "items": {
                            "type": "number"
                        }
                    },
                    "affine_terms": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/VectorAffineTerm"
                        }
                    },
                    "quadratc_terms": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/VectorQuadraticTerm"
                        }
                    }
                }
            }]
        },
        "scalar_sets": {
            "description": "A schema for the scalar-valued sets defined by MathOptFormat. See http: //www.juliaopt.org/MathOptInterface.jl/v0.8/apireference/#Sets-1 for a list of the sets and their meanings.",
            "type": "object",
            "required": ["head"],
            "oneOf": [{
                "required": ["upper"],
                "properties": {
                    "head": {
                        "const": "LessThan"
                    },
                    "upper": {
                        "type": "number"
                    }
                }
            }, {
                "required": ["lower"],
                "properties": {
                    "head": {
                        "const": "GreaterThan"
                    },
                    "lower": {
                        "type": "number"
                    }
                }
            }, {
                "required": ["value"],
                "properties": {
                    "head": {
                        "const": "EqualTo"
                    },
                    "value": {
                        "type": "number"
                    }
                }
            }, {
                "required": ["lower", "upper"],
                "properties": {
                    "head": {
                        "enum": ["Interval", "Semiinteger", "Semicontinuous"]
                    },
                    "lower": {
                        "type": "number"
                    },
                    "upper": {
                        "type": "number"
                    }
                }
            }, {
                "properties": {
                    "head": {
                        "enum": ["ZeroOne", "Integer"]
                    }
                }
            }]
        },
        "vector_sets": {
            "description": "A schema for the vector-valued sets defined by MathOptFormat. See http: //www.juliaopt.org/MathOptInterface.jl/v0.8/apireference/#Sets-1 for a list of the sets and their meanings.",
            "type": "object",
            "required": ["head"],
            "oneOf": [{
                "properties": {
                    "head": {
                        "enum": ["ExponentialCone", "DualExponentialCone"]
                    }
                }
            }, {
                "required": ["weights"],
                "properties": {
                    "head": {
                        "enum": ["SOS1", "SOS2"]
                    },
                    "weights": {
                        "type": "array",
                        "items": {
                            "type": "number"
                        }
                    }
                }
            }, {
                "required": ["dimension"],
                "properties": {
                    "head": {
                        "enum": [
                            "Zeros", "Reals", "Nonpositives", "Nonnegatives",
                            "SecondOrderCone", "RotatedSecondOrderCone",
                            "GeometricMeanCone"
                        ]
                    },
                    "dimension": {
                        "type": "integer",
                        "minimum": 1
                    }
                }
            }, {
                "required": ["side_dimension"],
                "properties": {
                    "head": {
                        "enum": [
                            "RootDetConeTriangle", "RootDetConeSquare",
                            "LogDetConeTriangle", "LogDetConeSquare",
                            "PositiveSemidefiniteConeTriangle",
                            "PositiveSemidefiniteConeSquare"
                        ]
                    },
                    "side_dimension": {
                        "type": "integer",
                        "minimum": 1
                    }
                }
            }, {
                "required": ["exponent"],
                "properties": {
                    "head": {
                        "enum": ["PowerCone", "DualPowerCone"]
                    },
                    "exponent": {
                        "type": "number"
                    }
                }
            }]
        }
    }
}

=== odow/MathOptFormat.jl/src/MOF/schema/examples/quadratic.mof.json
{
    "description": "The problem: min{x^2 + x * y + y^2}",
    "version": 0,
    "variables": [{
        "name": "x"
    }, {
        "name": "y"
    }],
    "objectives": [{
        "sense": "min",
        "function": {
            "head": "ScalarQuadraticFunction",
            "affine_terms": [],
            "quadratic_terms": [{
                    "coefficient": 1,
                    "variable_1": "x",
                    "variable_2": "x"
                },
                {
                    "coefficient": 2,
                    "variable_1": "x",
                    "variable_2": "y"
                },
                {
                    "coefficient": 1,
                    "variable_1": "y",
                    "variable_2": "y"
                }
            ],
            "constant": 0
        }
    }],
    "constraints": []
}

=== odow/MathOptFormat.jl/src/MOF/schema/examples/nlp.json
{
    "description": "The problem: min{2x + sin(x)^2 + y}.",
    "version": 0,
    "variables": [{
        "name": "x"
    }, {
        "name": "y"
    }],
    "objectives": [{
        "sense": "min",
        "function": {
            "head": "Nonlinear",
            "root": {
                "head": "node",
                "index": 4
            },
            "node_list": [{
                "head": "*",
                "args": [{
                    "head": "real",
                    "value": 2
                }, {
                    "head": "variable",
                    "name": "x"
                }]
            }, {
                "head": "sin",
                "args": [{
                    "head": "variable",
                    "name": "x"
                }]
            }, {
                "head": "^",
                "args": [{
                    "head": "node",
                    "index": 2
                }, {
                    "head": "real",
                    "value": 2
                }]
            }, {
                "head": "+",
                "args": [{
                    "head": "node",
                    "index": 1
                }, {
                    "head": "node",
                    "index": 3
                }, {
                    "head": "variable",
                    "name": "y"
                }]
            }]
        }
    }],
    "constraints": []
}

=== odow/MathOptFormat.jl/src/MOF/schema/examples/vector.json
{
    "description": "The problem: min{0 | [1 2; 3 4][x, y] + [5, 6] âˆˆ R+.",
    "version": 0,
    "variables": [{
        "name": "x"
    }, {
        "name": "y"
    }],
    "objectives": [],
    "constraints": [{
        "function": {
            "head": "VectorAffineFunction",
            "terms": [{
                "output_index": 1,
                "scalar_term": {
                    "coefficient": 1,
                    "variable": "x"
                }
            }, {
                "output_index": 1,
                "scalar_term": {
                    "coefficient": 2,
                    "variable": "y"
                }
            }, {
                "output_index": 2,
                "scalar_term": {
                    "coefficient": 3,
                    "variable": "x"
                }
            }, {
                "output_index": 2,
                "scalar_term": {
                    "coefficient": 4,
                    "variable": "y"
                }
            }],
            "constants": [5, 6]
        },
        "set": {
            "head": "Nonnegatives",
            "dimension": 2
        }
    }]
}

=== odow/MathOptFormat.jl/src/MOF/schema/examples/milp.mof.json
{
    "description": "The problem: min{x | x + y >= 1, x ∈ [0, 1], y ∈ {0, 1}}",
    "version": 0,
    "variables": [{
        "name": "x",
        "primal_start": 0.0
    }, {
        "name": "y",
        "primal_start": 1.0
    }],
    "objectives": [{
        "sense": "min",
        "function": {
            "head": "SingleVariable",
            "variable": "x"
        }
    }],
    "constraints": [{
        "name": "x + y >= 1",
        "function": {
            "head": "ScalarAffineFunction",
            "terms": [{
                    "coefficient": 1,
                    "variable": "x"
                },
                {
                    "coefficient": 1,
                    "variable": "y"
                }
            ],
            "constant": 0
        },
        "set": {
            "head": "GreaterThan",
            "lower": 1
        }
    }, {
        "name": "x ∈ [0, 1]",
        "function": {
            "head": "SingleVariable",
            "variable": "x"
        },
        "set": {
            "head": "Interval",
            "lower": 0,
            "upper": 1
        }
    }, {
        "name": "y ∈ {0, 1}",
        "function": {
            "head": "SingleVariable",
            "variable": "y"
        },
        "set": {
            "head": "ZeroOne"
        }
    }]
}

=== odow/MathOptFormat.jl/src/MOF/schema/examples/biobjective.mof.json
{
    "description": "The problem: [min{2x - y + 1}, max{y}]",
    "version": 0,
    "variables": [{
        "name": "x"
    }, {
        "name": "y"
    }],
    "objectives": [{
        "sense": "min",
        "function": {
            "head": "ScalarAffineFunction",
            "terms": [{
                    "coefficient": 2,
                    "variable": "x"
                },
                {
                    "coefficient": -1,
                    "variable": "y"
                }
            ],
            "constant": 1
        }
    }, {
        "sense": "max",
        "function": {
            "head": "SingleVariable",
            "variable": "y"
        }
    }],
    "constraints": []
}
